### PR TITLE
Expose stop method for Consumer

### PR DESCRIPTION
**Pull request by myNameIsPatrick**
## Description

Exposes the stop method for the underlying adc-streaming Consumer class.

## Checklist

* [x] All new functions and classes are documented and adhere to Google doc style (3.8.3-3.8.6 of [this](http://google.github.io/styleguide/pyguide.html#383-functions-and-methods) document)
* [x] Add/update sphinx documentation with any relevant changes.
* [x] Add/update pytest-style tests in `/tests`, ensuring sufficient code coverage.
* [x] `make test` runs without errors.
* [x] `make lint` doesn't give any warnings.
* [x] `make format` doesn't give any code formatting suggestions.
* [x] `make doc` runs without errors and generated docs render correctly.
* [x] Check that CI pipeline run on this PR passes all stages.
* [x] Review signoff by at least one developer.

NOTE: If this PR relates to a release, open and reference an issue with the Release checklist template.

### CODE REVIEW

**Comment by myNameIsPatrick** [comment]
Note: I could add test coverage using a mock, but this won't sufficiently test the method in question as the underlying adc-streaming Consumer class is being mocked in all tests. Any suggestions?

**Comment by cnweaver** [comment]
I think that at the level of a hop-client-specific unit test it can be considered sufficient to test that the method does in fact pass through to the lower-level (adc) consumer; after all what we're really expecting is that adc-streaming will also just pass through to confluent-kafka-python, and that that will pass the call through to librdkafka, which will actually do the right thing. It doesn't seem crazy to verify that the new code correctly forms the newest link in that chain, rather than worrying about trying to test whether the implementation buried in librdkafka really does stop its internal loop.

**Comment by myNameIsPatrick** [comment]
That's good enough for me. I've added the relevant test.

**Review by cnweaver — APPROVED** [review]
LGTM!

**Pull request merged**
