### PR TITLE
Add OAUTHBEARER/OIDC support

### PR DESCRIPTION
**Pull request by lpsinger**
## Description

Add OAUTHBEARER / OpenID Connect (OIDC) support as described in [KIP-768]. This is the authentication mechanism used by the GCN/TACH Kafka broker.

Depends on astronomy-commons/adc-streaming#53.

## Checklist

* [ ] All new functions and classes are documented and adhere to Google doc style (3.8.3-3.8.6 of [this](http://google.github.io/styleguide/pyguide.html#383-functions-and-methods) document)
* [ ] Add/update sphinx documentation with any relevant changes.
* [ ] Add/update pytest-style tests in `/tests`, ensuring sufficient code coverage.
* [ ] `make test` runs without errors.
* [x] `make lint` doesn't give any warnings.
* [x] `make format` doesn't give any code formatting suggestions.
* [ ] `make doc` runs without errors and generated docs render correctly.
* [ ] Check that CI pipeline run on this PR passes all stages.
* [ ] Review signoff by at least one developer.

NOTE: If this PR relates to a release, open and reference an issue with the Release checklist template.

### CODE REVIEW

**Comment by cnweaver** [comment]
Hi @lpsinger , thanks for this patch; this capability seems like a good addition to me. It looks like the existing tests aren't quite passing, though, and I imagine one or more additional ones will be needed to cover this new functionality. Is there anything I can do to help with that?

**Comment by lpsinger** [comment]
> Hi @lpsinger , thanks for this patch; this capability seems like a good addition to me. It looks like the existing tests aren't quite passing, though, and I imagine one or more additional ones will be needed to cover this new functionality. Is there anything I can do to help with that?

It's clear enough why the tests are failing; I'll fix them presently. Meanwhile would you please review (or identify a reviewer for) astronomy-commons/adc-streaming#53, which now has a unit test?

**Comment by cnweaver** [comment]
Glad to hear the test failure is simple. 

For the adc-stream PR, I'm unfortunately not able to review, but I am trying to get someone who can to take a look as soon as possible.

**Comment by lpsinger** [comment]
> Glad to hear the test failure is simple.

The tests are passing now, but in order to add a new test for the new features, we have to wait for the adc-streaming support to land.

**Comment by lpsinger** [comment]
I was thinking that when you are adding auth credentials interactively it would be better if it first asked you what _kind_ of credentials you wanted to add, rather than guessing based on whether or not you provided an OIDC token endpoint. What do you think of adding a small dependency to add a nice TUI here?

This demo uses [questionary](https://github.com/tmbo/questionary) which is based on [prompt_toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit), which has a very wide install base because it is required by IPython.

hop

**Comment by lpsinger** [comment]
Ping! Is it alright to add a dependency on questionary for this?

**Comment by adambrazier** [comment]
Sorry for late reply @lpsinger I had thought email response would work (but apparently not). At this stage, as we build our strategy for the next few months, we don't want to add dependencies to support CLI convenience features (our UX work right now is in the web interface to Hopskotch). That might change once we have our direction hammered out

**Review by cnweaver — CHANGES_REQUESTED** [review]
As a minor point, I'm seeing hop/auth.py:251 not being covered by the tests; it would be good to add a test or extend one of the existing ones (probably `test_load_auth_options` in `tests/test_auth.py`?) to cover that, not because I doubt that it works but just to keep our test coverage maximal. 

Otherwise, this patch looks fine.

**Comment by lpsinger** [comment]
> As a minor point, I'm seeing hop/auth.py:251 not being covered by the tests; it would be good to add a test or extend one of the existing ones (probably `test_load_auth_options` in `tests/test_auth.py`?) to cover that, not because I doubt that it works but just to keep our test coverage maximal.

Should be fixed now.

**Comment by lpsinger** [comment]
Ping... it's been a couple of weeks.

**Review by cnweaver — APPROVED** [review]
Sorry about the delay, this now looks fine.

**Comment by lpsinger** [comment]
Thank you! When will this be in a release?

**Comment by cnweaver** [comment]
We don't have a specific schedule; I would like to also get https://github.com/scimma/hop-client/issues/184 addressed before making another release (which should be easy as I've already written the code; the test just need updating to match). Other than that, we can probably do it in of order a week if no surprises happen (no specific need to go faster or wait for something else).

**Comment by cmessick** [comment]
Hi Chris, would it be possible to get a release by the end of this week? It's okay if not, I just wanted to check.

**Comment by cnweaver** [comment]
I'm afraid I can't promise; since I said we could do it 'anytime' I discovered that we are blocked by the last release of adc-streaming being incomplete (not yet on PyPI), which can't be solved until either someone else deals with it, or grants me the access to do it. I've requested this, but it may not come together by the end of this week.

**Comment by cmessick** [comment]
Okay Chris, no worries! Thanks for the explanation, we're hoping to make a release ourselves in a few weeks but I think everyone involved will understand if we're just at the end of a chain of packages that need to make releases before we can pull the trigger.

**Comment by cnweaver** [comment]
This is partially done: hop-client v0.7.0 is released on [GitHub](https://github.com/scimma/hop-client/releases/tag/v0.7.0) and [PyPI](https://pypi.org/project/hop-client/0.7.0/). The release on conda-forge will take a little longer, but my impression is that few if any people use that, so hopefully the delay on that isn't a problem.

**Comment by lpsinger** [comment]
Thank you!

**Comment by adambrazier** [comment]
Chris is traveling this week for IceCube meeting; I think at this point (as we undergo some discussions about immediate strategy) we don’t want to add requirements to create convenience functions for the CLI, but this is just an interim decision

**Pull request merged**
